// Copyright (C) 2026 by Lucas Gomes <lucasgsm88@gmail.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! The Lucide icon font — route (b) from `spec/architecture/editor-ui-visual-redesign.md`'s
//! "Icon set" section: Private-Use-Area codepoints in a dedicated [`egui::FontFamily`],
//! rendered exactly like every existing single-glyph icon in this codebase already is (via
//! `RichText`/`painter.text`), not a separate SVG-to-texture pipeline.
//!
//! `assets/fonts/lucide-oca.ttf` and its name→codepoint mapping (`lucide-oca.json`) are
//! generated by `tools/icon-font/build-icon-font.ts` from the vendored SVGs in
//! `spec/architecture/assets/icons/` — see that script's own doc comment to regenerate after
//! adding/removing an icon (`make icon-font`). The `char` constants below are hand-written for
//! ergonomic call sites (`icons::LOCK` beats a string lookup at every use site); [`tests`]
//! checks them against the embedded JSON mapping so a regenerated font with different
//! codepoints fails a test instead of silently drawing the wrong glyph.
//!
//! `#![allow(dead_code)]`: most constants (and, outside `cfg(test)`, the embedded JSON string)
//! have no call site yet — wiring individual screens over from their current emoji/text glyphs
//! is a separate, per-screen slice of work (see the redesign doc's Icon set section). `ui` is a
//! bin crate, so nothing external proves these `pub` items reachable the way a lib crate's
//! would be; this is a deliberately-ahead-of-its-call-sites public API surface, not actually-
//! dead code.
#![allow(dead_code)]

use egui::{FontData, FontDefinitions, FontFamily};
use std::sync::Arc;

/// The dedicated font family name every icon call site renders through, e.g.
/// `RichText::new(icons::LOCK).family(icons::family())`.
pub fn family() -> FontFamily {
    FontFamily::Name("lucide-oca".into())
}

const FONT_BYTES: &[u8] = include_bytes!("../assets/fonts/lucide-oca.ttf");
const CODEPOINTS_JSON: &str = include_str!("../assets/fonts/lucide-oca.json");

/// Registers the icon font with egui. Call once at startup, alongside [`crate::theme::apply`].
pub fn install(ctx: &egui::Context) {
    let mut fonts = FontDefinitions::default();
    fonts.font_data.insert(
        "lucide-oca".to_owned(),
        Arc::new(FontData::from_static(FONT_BYTES)),
    );
    fonts
        .families
        .insert(family(), vec!["lucide-oca".to_owned()]);
    ctx.set_fonts(fonts);
}

// One `char` per vendored icon (`spec/architecture/assets/icons/*.svg`), matching
// `assets/fonts/lucide-oca.json`'s name→codepoint mapping.
pub const CAMERA: char = '\u{E000}';
pub const CHEVRON_DOWN: char = '\u{E001}';
pub const CHEVRON_LEFT: char = '\u{E002}';
pub const CHEVRON_RIGHT: char = '\u{E003}';
pub const ELLIPSIS_VERTICAL: char = '\u{E004}';
pub const EYE: char = '\u{E005}';
pub const EYE_OFF: char = '\u{E006}';
pub const FAST_FORWARD: char = '\u{E007}';
pub const FOLD_HORIZONTAL: char = '\u{E008}';
pub const HAND: char = '\u{E009}';
pub const LOCK: char = '\u{E00A}';
pub const LOCK_OPEN: char = '\u{E00B}';
pub const MOUSE_POINTER_2: char = '\u{E00C}';
pub const MUSIC: char = '\u{E00D}';
pub const PAUSE: char = '\u{E00E}';
pub const PLAY: char = '\u{E00F}';
pub const REPEAT: char = '\u{E010}';
pub const REWIND: char = '\u{E011}';
pub const SCISSORS: char = '\u{E012}';
pub const SETTINGS: char = '\u{E013}';
pub const SKIP_BACK: char = '\u{E014}';
pub const SKIP_FORWARD: char = '\u{E015}';
pub const TYPE: char = '\u{E016}';
pub const UPLOAD: char = '\u{E017}';
pub const WAND_SPARKLES: char = '\u{E018}';

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    /// Every hand-written `char` constant above must match the generated JSON mapping exactly
    /// — this is what catches a `make icon-font` rerun reassigning a codepoint (it shouldn't,
    /// per the script's stability guarantee, but this is the cheap check that it didn't) out
    /// from under a constant nobody remembered to update.
    #[test]
    fn constants_match_generated_mapping() {
        let mapping: BTreeMap<String, u32> =
            serde_json::from_str(CODEPOINTS_JSON).expect("lucide-oca.json should be valid JSON");

        let constants: BTreeMap<&str, char> = BTreeMap::from([
            ("camera", CAMERA),
            ("chevron-down", CHEVRON_DOWN),
            ("chevron-left", CHEVRON_LEFT),
            ("chevron-right", CHEVRON_RIGHT),
            ("ellipsis-vertical", ELLIPSIS_VERTICAL),
            ("eye", EYE),
            ("eye-off", EYE_OFF),
            ("fast-forward", FAST_FORWARD),
            ("fold-horizontal", FOLD_HORIZONTAL),
            ("hand", HAND),
            ("lock", LOCK),
            ("lock-open", LOCK_OPEN),
            ("mouse-pointer-2", MOUSE_POINTER_2),
            ("music", MUSIC),
            ("pause", PAUSE),
            ("play", PLAY),
            ("repeat", REPEAT),
            ("rewind", REWIND),
            ("scissors", SCISSORS),
            ("settings", SETTINGS),
            ("skip-back", SKIP_BACK),
            ("skip-forward", SKIP_FORWARD),
            ("type", TYPE),
            ("upload", UPLOAD),
            ("wand-sparkles", WAND_SPARKLES),
        ]);

        assert_eq!(
            mapping.len(),
            constants.len(),
            "lucide-oca.json and this module's constants list a different number of icons — \
             one was updated without the other"
        );
        for (name, codepoint) in &mapping {
            let expected = char::from_u32(*codepoint).expect("codepoint should be valid char");
            let actual = constants.get(name.as_str()).unwrap_or_else(|| {
                panic!("lucide-oca.json has icon `{name}` with no matching constant in icons.rs")
            });
            assert_eq!(
                *actual, expected,
                "icons::{name} constant doesn't match lucide-oca.json's codepoint for `{name}`"
            );
        }
    }
}
